name: indodax
description: A simple Indodax API Client.
version: 1.0.0
homepage: https://ikhwanperwira.my.id

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  crypto: ^3.0.1
  http: ^0.13.4
