name: indodax
description: A simple asynchronous Indodax API Client. Support PrivateAPI and PublicAPI.
version: 1.1.1
homepage: https://ikhwanperwira.my.id
repository: https://github.com/wawan-ikhwan/indodax

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  crypto: ^3.0.1
  http: ^0.13.4
  universal_io: ^2.0.4
